package: simple_saml
version: '1.2'

page:
    title: 'translate:simple_saml'
    perm: admin[]
    pjax: true
    subpages:
        profiles:
            title: 'translate:profiles'
        docs:
            title: translate:readme
            subPath: README.md
            icon: rex-icon fa-book
            itemclass: pull-right


requires:
    packages:
        yform: '^3'
        ycom: '^4'
    redaxo: '^5.11'
