package: simple_saml
version: '1.1'

page:
    title: 'translate:simple_saml'
    perm: admin[]
    pjax: true
    subpages:
        profiles:
            title: 'translate:profiles'
        readme:
            title: 'translate:readme'
            icon: rex-icon fa-info-circle
            itemclass: pull-right

requires:
    packages:
        yform: '^3'
        ycom: '^4'
    redaxo: '^5.11'
