name: PHP Checks

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:

    phpstan-analysis:
        name: phpstan static code analysis
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: intl, imagick
                  coverage: none # disable xdebug, pcov
            - name: Install Dependencies
              run: composer install --ansi --prefer-dist
            - run: |
                  vendor/bin/phpstan analyse --ansi --no-progress
